services:
  - type: web
    name: cybersportorg
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cybersportorg-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@cybersport.org
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: cybersportorg-db
    plan: free
    region: frankfurt
    databaseName: cybersportorg
    user: cybersportorg
